# docker-compose versão 2
version: '2'

# Serviços
services:

  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/vhost.conf:/etc/nginx/conf.d/default.conf
      - logs-web:/var/log/nginx
      - /var/www/html:/var/www/html
    links:
      - php:php
    restart: always
    network_mode: bridge

  # php-fpm
  php:
    build: .
    expose:
      - "9000"
    volumes:
      - /var/www/html:/var/www/html
      - logs-php-fpm:/var/log/php-fpm
    links:
      - redis:redis
      - elasticsearch:elasticsearch
      - gearman:gearman
      - postgres:postgres
    restart: always
    network_mode: bridge

  # redis
  redis:
    image: redis
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    restart: always
    network_mode: bridge

  # elasticsearch
  elasticsearch:
    image: elasticsearch:1.7
    expose:
      - "9200"
      - "9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: always
    network_mode: bridge

  # logstash
  logstash:
    image: logstash:1.5
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    links:
      - redis:redis
      - elasticsearch:elasticsearch
    volumes:
      - ./conf/logstash.conf:/etc/logstash/conf.d/logstash.conf
    restart: always
    network_mode: bridge

  # gearman
  gearman:
    image: kendu/gearman
    expose:
      - "4730"
    restart: always
    network_mode: bridge

  # postgres
  postgres:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: admin
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    network_mode: bridge

# Volumes
volumes:
  redis-data:
    driver: local
  elasticsearch-data:
    driver: local
  logs-php-fpm:
    driver: local
  logs-web:
    driver: local
  pg-data:
    driver: local
