front:
  build: .
  ports:
    - "80:80"
    - "443:443"
  links:
    - redis:redis
    - elasticsearch:elasticsearch
    - gearman:gearman
  volumes:
    - /var/www/html:/var/www/html

redis:
  image: redis
  ports:
    - "6379:6379"

elasticsearch:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  image: logstash:1.5
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  links:
    - redis:redis
    - elasticsearch:elasticsearch
  volumes:
    - ./conf/logstash.conf:/etc/logstash/conf.d/logstash.conf

gearman:
    image: kendu/gearman
    ports:
        - '4730:4730'
